@startuml overview
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/Groups/VPC.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Groups/PublicSubnet.puml
!include AWSPuml/Groups/PrivateSubnet.puml
!include AWSPuml/Groups/SecurityGroup.puml
!include AWSPuml/Groups/Generic.puml
!include AWSPuml/General/User.puml
!include AWSPuml/Containers/ElasticKubernetesService.puml
!include AWSPuml/Compute/EC2Instance.puml
!include AWSPuml/Containers/Containers.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/NetworkingContentDelivery/ElasticLoadBalancingApplicationLoadBalancer.puml

top to bottom direction

skinparam shadowing false
hide stereotype
skinparam linetype ortho
skinparam rectangle {
    BackgroundColor AWS_BG_COLOR
    BorderColor transparent
}

rectangle "$UserIMG()\nClient" as client

AWSCloudGroup(cloud){
  VPCGroup(vpc) {
      PublicSubnetGroup(public_subnet, "Public Subnet") {
        SecurityGroupGroup(sg, "Security Group") #Transparent {
          rectangle "$ElasticLoadBalancingApplicationLoadBalancerIMG()" as alb #Transparent
        }
      }
      PrivateSubnetGroup(private_subnet, "Private Subnet") {
        GenericGroup(eks_cluster, "EKS Cluster") #Transparent {
          rectangle "$ElasticKubernetesServiceIMG()" as eks #Transparent
          GenericGroup(eks_node1, "Node1") #Transparent {
             rectangle "$ContainersIMG()\nSolr" as solr1 #Transparent
          }
          GenericGroup(eks_node2, "Node2") #Transparent {
            rectangle "$ContainersIMG()\nSolr" as solr2 #Transparent
          }
          GenericGroup(eks_node3, "Node3") #Transparent {
            rectangle "$ContainersIMG()\nSearch API" as search_api #Transparent
            rectangle "$ContainersIMG()\nIndexer" as indexer #Transparent
          }
        }
      }
  }
  rectangle "$SimpleStorageServiceIMG()" as s3
}

client-r->alb
alb-->search_api
search_api->solr1
search_api->solr2
s3-r->indexer
indexer-->solr1
indexer-->solr2
@enduml
